# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

readme_file = 'README.md'
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'databind.core >=0.9.0,<1.0.0',
  'glob2 >=0.6.0,<0.7.0',
  'nodepy-runtime >=2.1.5,<2.2.0',
  'nr.collections >=0.1.1,<1.0.0',
  'nr.interface >=0.0.1,<0.1.0',
  'nr.fs >=1.1.1,<2.0.0',
  'nr.stream >=0.0.1,<0.1.0',
  'nr.sumtype >=0.0.1,<0.1.0',
  'requests >=2.19.1,<3.0.0',
  'termcolor >=1.1.0,<2.0.0',
  'toml >=0.9.4,<1.0.0',
  'werkzeug >=0.14.1,<1.0.0',
]

setuptools.setup(
  name = 'craftr',
  version = '4.0.0',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'A Python based meta build system for various languages.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = 'https://github.com/craftr-build/craftr',
  license = 'MIT',
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = '>=3.6.0,<4.0.0',
  data_files = [],
  entry_points = {
    'console_scripts': [
      'craftr = craftr.main:main',
    ]
  },
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = True,
)
