# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

readme_file = 'readme.md'
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'craftr-core >=0.1.0,<0.2.0',
  'craftr-dsl >=0.2.0,<0.3.0',
]

setuptools.setup(
  name = 'craftr-build',
  version = '5.0.0',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'CLI and DSL frontend for the Craftr build system.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = None,
  license = None,
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = '>=3.8.0,<4.0.0',
  data_files = [],
  entry_points = {
    'craftr.plugins': [
      'cxx = craftr.build.plugins.cxx',
      'run = craftr.build.plugins.run',
      'processor = craftr.build.plugins.processor',
      'haskell = craftr.build.plugins.haskell',
      'ocaml = craftr.build.plugins.ocaml',
    ],
    'console_scripts': [
      'craftr = craftr.build.main:main',
    ]
  },
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = False,
)
