# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

requirements = []

setuptools.setup(
  name = 'craftr-build',
  version = '0.0.0',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'Package description here.',
  long_description = None,
  long_description_content_type = None,
  url = None,
  license = None,
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = {},
  tests_require = [],
  python_requires = '>=3.9.0,<4.0.0',
  data_files = [],
  entry_points = {
    'craftr.plugins': [
      'default = craftr.build.plugins.default',
      'cxx = craftr.build.plugins.cxx',
    ],
    'console_scripts': [
      'craftr = craftr.build.main:main',
    ]
  },
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = False,
)
