name: craftr-core
version: 0.1.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
modulename: craftr.core
description: The pure Python API for describing and executing builds with Craftr.
typed: true
requirements:
- nr.caching ^0.3.2
- python ^3.8
- typing-extensions ^3.10.0.0
